Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.10
    Architectures:
    - x86_64
    Handler: function.lambda_handler
    Timeout: 5
    Environment:
      Variables:
        S3_BUCKET: mas-thesis-datapipeline-platform
        SOURCE_HDB_RESALE_PRICES: source_data/resale-flat-prices-based-on-registration-date-from-jan-2017-onwards.csv
        SOURCE_MRT_STATIONS: source_data/mrt_stations.xlsx
        SOURCE_HDB_ADDRESS_GEODATA: source_data/address_geolocations.csv
        LOCATION_STAGING: dp-lambda/staging
        LOCATION_STORAGE: dp-lambda/storage
        LOCATION_TRANSFORMED_ANALYTICS: dp-lambda/transformed_analytics
        LOCATION_ANALYTICS: dp-lambda/analytics
        API_OVERPASS: https://overpass-api.de/api/interpreter
        STORAGE_FILE_HDB_RESALE_PRICES: resale_flat_prices.csv
        STORAGE_FILE_MRT_STATIONS: mrt_stations.csv
        STORAGE_FILE_MRT_GEODATA: mrt_geodata.csv
        STORAGE_FILE_MALL_GEODATA: mall_geodata.csv
        STORAGE_FILE_HDB_ADDRESS_GEODATA: address_geodata.csv

Resources:
  S3FileAccessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/s3_file_access_layer/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: makefile

  ##### Extract Functions #####
  ExtractHdbResalePricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_hdb_resale_prices/
      FunctionName: ExtractHdbResalePrices
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  ExtractMrtStationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mrt_stations/
      FunctionName: ExtractMrtStations
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  ExtractHdbAddressGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_hdb_address_geodata/
      FunctionName: ExtractHdbAddressGeodata
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  ExtractMrtGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mrt_geodata/
      FunctionName: ExtractMrtGeodata
      Timeout: 20
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  ExtractMallGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mall_geodata/
      FunctionName: ExtractMallGeodata
      Timeout: 20
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess
  
  ##### Load Functions #####
  LoadHdbResalePricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_hdb_resale_prices/
      FunctionName: LoadHdbResalePrices
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  LoadMrtStationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_mrt_stations/
      FunctionName: LoadMrtStations
      Timeout: 15
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  LoadHdbAddressGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_hdb_address_geodata/
      FunctionName: LoadHdbAddressGeodata
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  LoadMallGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_mall_geodata/
      FunctionName: LoadMallGeodata
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess

  LoadMrtGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_mrt_geodata/
      FunctionName: LoadMrtGeodata
      Layers:
        - !Ref S3FileAccessLayer
      Policies:
      - AmazonS3FullAccess
