Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.10
    Architectures:
    - x86_64
    Handler: function.lambda_handler

Resources:
  # Extract Functions
  ExtractHdbResalePricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_hdb_resale_prices/
      FunctionName: ExtractHdbResalePrices
      Policies:
      - AmazonS3FullAccess
  ExtractMrtStationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mrt_stations/
      FunctionName: ExtractMrtStations
      Policies:
      - AmazonS3FullAccess
  ExtractHdbAddressGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_hdb_address_geodata/
      FunctionName: ExtractHdbAddressGeodata
      Policies:
      - AmazonS3FullAccess
  ExtractMrtGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mrt_geodata/
      FunctionName: ExtractMrtGeodata
      Timeout: 20
      Policies:
      - AmazonS3FullAccess
  ExtractMallGeodataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/extract/extract_mall_geodata/
      FunctionName: ExtractMallGeodata
      Timeout: 20
      Policies:
      - AmazonS3FullAccess
  
  # Load Functions  
  LoadHdbResalePricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load/load_hdb_resale_prices/
      FunctionName: LoadHdbResalePrices
      Policies:
      - AmazonS3FullAccess
