on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: SAM build
        run: sam build --use-container
      - name: SAM deploy
        run: >
          sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --stack-name sam-dp-lambda
          --s3-bucket ${{ vars.S3_BUCKET }}
          --s3-prefix build
          --capabilities CAPABILITY_IAM
          --region ${{ vars.AWS_REGION }}
          --image-repository 894604930168.dkr.ecr.ap-southeast-2.amazonaws.com/dp-lambda
